{
  "alignmentBaseline$name": "alignment-baseline",
  "alignmentBaseline$options": ["auto", "baseline", "before-edge", "text-before-edge", "middle", "central", "after-edge", "text-after-edge", "ideographic", "alphabetic", "hanging", "mathematical", "inherit"],
  "alignmentBaseline$value": "auto",
  "alignmentBaseline$exprString": "auto",
  "baselineShift$name": "baseline-shift",
  "baselineShift$options": ["auto", "baseline", "super", "sub", "<percentage>", "<length>", "inherit"],
  "baselineShift$value": "auto",
  "baselineShift$exprString": "auto",
  "direction$name": "direction",
  "direction$options": ["ltr", "rtl", "inherit"],
  "direction$value": "ltr",
  "direction$exprString": "ltr",
  "display$name": "display",
  "display$options": ["inline", "block", "list-item", "run-in", "compact", "marker", "table", "inline-table", "table-row-group", "table-header-group", "table-footer-group", "table-row", "table-column-group", "table-column", "table-cell", "table-caption", "none", "inherit"],
  "display$value": "inline",
  "display$exprString": "inline",
  "dominantBaseline$name": "dominant-baseline",
  "dominantBaseline$options": ["auto", "use-script", "no-change", "reset-size", "ideographic", "alphabetic", "hanging", "mathematical", "central", "middle", "text-after-edge", "text-before-edge", "inherit"],
  "dominantBaseline$value": "auto",
  "dominantBaseline$exprString": "auto",
  "fill$name": "fill",
  "fill$options": ["<paint>", "context-fill", "context-stroke"],
  "fill$value": "#ccc",
  "fill$exprString": "#ccc",
  "fillOpacity$name": "fill-opacity",
  "fillOpacity$options": [  "<opacity-value>", "inherit"],
  "fillOpacity$value": "1",
  "fillOpacity$exprString": "1",
  "fontFamily$name": "font-family",
  "fontFamily$options": [],
  "fontFamily$value": "inherit",
  "fontFamily$exprString": "inherit",
  "fontSize$name": "font-size",
  "fontSize$options": ["<absolute-size>", "<relative-size>", "<length>", "<percentage>", "inherit"],
  "fontSize$value": "inherit",
  "fontSize$exprString": "inherit",
  "fontStyle$name": "font-style",
  "fontStyle$options": ["normal", "italic", "oblique", "inherit"],
  "fontStyle$value": "normal",
  "fontStyle$exprString": "normal",
  "fontWeight$name": "font-weight",
  "fontWeight$options": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900", "inherit"],
  "fontWeight$value": "normal",
  "fontWeight$exprString": "normal",
  "opacity$name": "opacity",
  "opacity$options": ["<opacity-value>", "inherit"],
  "opacity$value": "1",
  "opacity$exprString": "1",
  "stroke$name": "stroke",
  "stroke$options": ["<paint>", "context-fill", "context-stroke"],
  "stroke$value": "steelblue",
  "stroke$exprString": "steelblue",
  "strokeOpacity$name": "stroke-opacity",
  "strokeOpacity$options": ["<opacity-value>", "inherit"],
  "strokeOpacity$value": "1",
  "strokeOpacity$exprString": "1",
  "strokeWidth$name": "stroke-width",
  "strokeWidth$options": ["<length>", "<percentage>", "inherit"],
  "strokeWidth$value": "1",
  "strokeWidth$exprString": "1",
  "textAnchor$name": "text-anchor",
  "textAnchor$options": ["start", "middle", "end", "inherit"],
  "textAnchor$value": "inherit",
  "textAnchor$exprString": "inherit",
  "textDecoration$name": "text-decoration",
  "textDecoration$options": ["none", "underline", "overline", "line-through", "blink", "inherit"],
  "textDecoration$value": "inherit",
  "textDecoration$exprString": "inherit",
  "visibility$name": "visibility",
  "visibility$options": ["visible", "hidden", "collapse", "inherit"],
  "visibility$value": "visible",
  "visibility$exprString": "visible",
}