export const initialState = {
  "drawing": {
    "data":[],
    "overallAttributes$xAxis$name": "X Axis",
    "overallAttributes$xAxis$type": "axis",
    "overallAttributes$xAxis$value": "undefined",
    "overallAttributes$xAxis$exprString": "",
    "overallAttributes$yAxis$name": "Y Axis",
    "overallAttributes$yAxis$type": "axis",
    "overallAttributes$yAxis$value": "undefined",
    "overallAttributes$yAxis$exprString": "",
    "overallAttributes$xAxis$scale": "linear",
    "overallAttributes$yAxis$scale": "linear",
    "overallAttributes$chartWidth$name": "Chart Width",
    "overallAttributes$chartWidth$value": 600,
    "overallAttributes$chartWidth$exprString": "600",
    "overallAttributes$chartHeight$name": "Chart Height",
    "overallAttributes$chartHeight$value": 400,
    "overallAttributes$chartHeight$exprString": "400",
    "overallAttributes$marginLeft$name": "Margin Left",
    "overallAttributes$marginLeft$value": 30,
    "overallAttributes$marginLeft$exprString": "30",
    "overallAttributes$marginRight$name": "Margin Right",
    "overallAttributes$marginRight$value": 30,
    "overallAttributes$marginRight$exprString": "30",
    "overallAttributes$marginBottom$name": "Margin Bottom",
    "overallAttributes$marginBottom$value": 30,
    "overallAttributes$marginBottom$exprString": "30",
    "overallAttributes$marginTop$name": "Margin Top",
    "overallAttributes$marginTop$value": 20,
    "overallAttributes$marginTop$exprString": "20",
    "overallAttributes$border$name": "border",
    "overallAttributes$border$value": "#f5f5f5",
    "overallAttributes$border$exprString": "#f5f5f5",
    "overallAttributes$alignmentBaseline$name": "alignment-baseline",
    "overallAttributes$alignmentBaseline$options": ["auto", "baseline", "before-edge", "text-before-edge", "middle", "central", "after-edge", "text-after-edge", "ideographic", "alphabetic", "hanging", "mathematical", "inherit"],
    "overallAttributes$alignmentBaseline$value": "auto",
    "overallAttributes$alignmentBaseline$exprString": "auto",
    "overallAttributes$baselineShift$name": "baseline-shift",
    "overallAttributes$baselineShift$options": ["auto", "baseline", "super", "sub", "<percentage>", "<length>", "inherit"],
    "overallAttributes$baselineShift$value": "auto",
    "overallAttributes$baselineShift$exprString": "auto",
    "overallAttributes$direction$name": "direction",
    "overallAttributes$direction$options": ["ltr", "rtl", "inherit"],
    "overallAttributes$direction$value": "ltr",
    "overallAttributes$direction$exprString": "ltr",
    "overallAttributes$display$name": "display",
    "overallAttributes$display$options": ["inline", "block", "list-item", "run-in", "compact", "marker", "table", "inline-table", "table-row-group", "table-header-group", "table-footer-group", "table-row", "table-column-group", "table-column", "table-cell", "table-caption", "none", "inherit"],
    "overallAttributes$display$value": "inline",
    "overallAttributes$display$exprString": "inline",
    "overallAttributes$dominantBaseline$name": "dominant-baseline",
    "overallAttributes$dominantBaseline$options": ["auto", "use-script", "no-change", "reset-size", "ideographic", "alphabetic", "hanging", "mathematical", "central", "middle", "text-after-edge", "text-before-edge", "inherit"],
    "overallAttributes$dominantBaseline$value": "auto",
    "overallAttributes$dominantBaseline$exprString": "auto",
    "overallAttributes$fill$name": "fill",
    "overallAttributes$fill$options": ["<paint>", "context-fill", "context-stroke"],
    "overallAttributes$fill$value": "#cacaca",
    "overallAttributes$fill$exprString": "#cacaca",
    "overallAttributes$fillOpacity$name": "fill-opacity",
    "overallAttributes$fillOpacity$options": [  "<opacity-value>", "inherit"],
    "overallAttributes$fillOpacity$value": "1",
    "overallAttributes$fillOpacity$exprString": "1",
    "overallAttributes$fontFamily$name": "font-family",
    "overallAttributes$fontFamily$options": [],
    "overallAttributes$fontFamily$value": "inherit",
    "overallAttributes$fontFamily$exprString": "inherit",
    "overallAttributes$fontSize$name": "font-size",
    "overallAttributes$fontSize$options": ["<absolute-size>", "<relative-size>", "<length>", "<percentage>", "inherit"],
    "overallAttributes$fontSize$value": "inherit",
    "overallAttributes$fontSize$exprString": "inherit",
    "overallAttributes$fontStyle$name": "font-style",
    "overallAttributes$fontStyle$options": ["normal", "italic", "oblique", "inherit"],
    "overallAttributes$fontStyle$value": "normal",
    "overallAttributes$fontStyle$exprString": "normal",
    "overallAttributes$fontWeight$name": "font-weight",
    "overallAttributes$fontWeight$options": ["normal", "bold", "bolder", "lighter", "100", "200", "300", "400", "500", "600", "700", "800", "900", "inherit"],
    "overallAttributes$fontWeight$value": "normal",
    "overallAttributes$fontWeight$exprString": "normal",
    "overallAttributes$opacity$name": "opacity",
    "overallAttributes$opacity$options": ["<opacity-value>", "inherit"],
    "overallAttributes$opacity$value": "1",
    "overallAttributes$opacity$exprString": "1",
    "overallAttributes$stroke$name": "stroke",
    "overallAttributes$stroke$options": ["<paint>", "context-fill", "context-stroke"],
    "overallAttributes$stroke$value": "steelblue",
    "overallAttributes$stroke$exprString": "steelblue",
    "overallAttributes$strokeOpacity$name": "stroke-opacity",
    "overallAttributes$strokeOpacity$options": ["<opacity-value>", "inherit"],
    "overallAttributes$strokeOpacity$value": "1",
    "overallAttributes$strokeOpacity$exprString": "1",
    "overallAttributes$strokeWidth$name": "stroke-width",
    "overallAttributes$strokeWidth$options": ["<length>", "<percentage>", "inherit"],
    "overallAttributes$strokeWidth$value": "1",
    "overallAttributes$strokeWidth$exprString": "1",
    "overallAttributes$textAnchor$name": "text-anchor",
    "overallAttributes$textAnchor$options": ["start", "middle", "end", "inherit"],
    "overallAttributes$textAnchor$value": "inherit",
    "overallAttributes$textAnchor$exprString": "inherit",
    "overallAttributes$textDecoration$name": "text-decoration",
    "overallAttributes$textDecoration$options": ["none", "underline", "overline", "line-through", "blink", "inherit"],
    "overallAttributes$textDecoration$value": "inherit",
    "overallAttributes$textDecoration$exprString": "inherit",
    "overallAttributes$visibility$name": "visibility",
    "overallAttributes$visibility$options": ["visible", "hidden", "collapse", "inherit"],
    "overallAttributes$visibility$value": "visible",
    "overallAttributes$visibility$exprString": "visible",
    "overallAttributes$ownStyleList": ["border", "alignmentBaseline", "baselineShift", "direction", "display", "dominantBaseline", "fill", "fillOpacity", "fontFamily", "fontSize", "fontStyle", "fontWeight", "opacity", "stroke", "strokeOpacity", "strokeWidth", "textAnchor", "textDecoration", "visibility"],
    "overallAttributes$inheritedStyleList": [],
    "overallAttributes$ownDimensionList": ["chartWidth", "chartHeight", "marginLeft", "marginTop", "marginRight", "marginBottom"],
    "overallAttributes$axisList": ["xAxis", "yAxis"],
    "overallAttributes$inheritedDimensionList": [],
    "overallAttributes$whatAmI": "overallAttributes",
    "hoveredAttributeId": "",
    "beingDrawn": false,
    "currentShape": "rect",
    "activeLayerId" : "",
    "activeShapeId" : "",
    "layerIds": [],
  },
  "file": {
    "isLoaded": false,
  },
};
